EXTENSION = borealisx2        # the extensions name
DATA = borealisx2--0.0.1.sql  # script files to install
MODULES = borealisx2

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)